// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvYYE91vLCuG9d58duwZfP02mjjNDoBDg',
    appId: '1:5219550061:web:fa2ce674ed12b29bffd064',
    messagingSenderId: '5219550061',
    projectId: 'tiktok-e499b',
    authDomain: 'tiktok-e499b.firebaseapp.com',
    storageBucket: 'tiktok-e499b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfn1zMNzItuz22qZD9wGA_ifj1-Pz9kiE',
    appId: '1:5219550061:android:c69f847d0d919a29ffd064',
    messagingSenderId: '5219550061',
    projectId: 'tiktok-e499b',
    storageBucket: 'tiktok-e499b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT-95VebJTh08-zKbH-bIzx2H_AXHUpJI',
    appId: '1:5219550061:ios:510f3000747e7e31ffd064',
    messagingSenderId: '5219550061',
    projectId: 'tiktok-e499b',
    storageBucket: 'tiktok-e499b.appspot.com',
    iosClientId: '5219550061-fbvoiesja8k91ujaqpoed4puenjbgklj.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktok',
  );
}
